export { FB } from "./navbar/ic_fb";
export { Ic_world } from "./navbar/ic_world";
export { Ic_down } from "./navbar/ic_down";
export { Ic_Right_Arrow } from "./navbar/ic_right_arrow";
export { Tweet } from "./navbar/ic_twitter";
export { LinkedIn } from "./navbar/ic_linkedIn";
export { Tictok } from "./navbar/ic_tictok";
export { Youtube } from "./navbar/ic_youtube";
export { RightFilledArrow } from "./navbar/ic_right_filled_arrow";
